# requirements.yml
collections:
  - name: community.general   # nftables, cron, psql, …
    version: ">=8.4.0"
  - name: ansible.posix       # misc POSIX helpers, also has nftables these days
    version: ">=1.5.0"