---
- name: Apply netplan
  ansible.builtin.command: netplan apply

- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted

- name: ldconfig
  ansible.builtin.command: ldconfig

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload
