---
# roles/firewall/tasks/install.yml
# Installs nftables, ipset and Netify – updates cache only when required
###############################################################################

# 1 ▸ Core packages -----------------------------------------------------------
#- name: Ensure nftables & ipset are present (refresh cache only if stale >24 h)
#  ansible.builtin.apt:
#    name:
#      - nftables
#      - ipset
#    state: latest
#    update_cache: yes
#    cache_valid_time: 86400        # seconds → refresh if older than 1 day

