###############################################################################
# Ensure that all ipsets referenced in dscp_rules exist (even if empty)
###############################################################################
- set_fact:
    ipset_names: "{{ dscp_rules | regex_findall('@([A-Za-z0-9_]+)') }}"

- name: Extract ipset names from dscp_rules
  set_fact:
    ipset_names: "{{ dscp_rules | regex_findall('@\"([^\"]+)\"') | list }}"

- name: Create required ipsets
  ansible.builtin.command: >
    ipset create "{{ item }}" hash:ip family inet timeout 0 -exist
  loop: "{{ ipset_names }}"
  register: ipset_create
  changed_when: "'created' in ipset_create.stdout"

# ---> nftables is reloaded ONLY if we created a new set or if the config changed
- name: (Re)load nftables ruleset
  ansible.builtin.command: nft -f /etc/nftables.conf
  when: ipset_create is changed or nftables_conf_updated | default(false)
  notify: Enable nftables service