###############################################################################
# Ensure that all ipsets referenced in dscp_rules exist (even if empty)
###############################################################################
- name: Extract ipset names from dscp_rules
  set_fact:
    ipset_names: "{{ dscp_rules | regex_findall('@\"([^\"]+)\"') | list }}"

- name: Gather ipset names from dscp_classes
  set_fact:
    ipset_names: "{{ ipset_names + (item.match.ndpi_sets | default([])) + (item.match.netify_sets | default([])) }}"
  loop: "{{ firewall_cfg.dscp_classes.values() }}"
  when: firewall_cfg.dscp_classes is defined

- name: Deduplicate ipset names
  set_fact:
    ipset_names: "{{ ipset_names | unique }}"

- name: Create required ipsets
  ansible.builtin.command: >
    ipset create "{{ item | regex_replace('[:\\.-]', '_') }}" hash:ip family inet timeout 0 -exist
  loop: "{{ ipset_names }}"
  register: ipset_create
  changed_when: "'created' in ipset_create.stdout"

# ---> nftables is reloaded ONLY if we created a new set or if the config changed
- name: (Re)load nftables ruleset
  ansible.builtin.command: nft -f /etc/nftables.conf
  when: ipset_create is changed or nftables_conf_updated | default(false)
  notify: Enable nftables service