---
# 0 ▸ System prerequisites
- import_tasks: install.yml        # packages + Netify

# 1 ▸ Kernel settings  (NAT needs forwarding)
- import_tasks: sysctl.yml         # ← new

# 2 ▸ Interface configuration
- import_tasks: netplan.yml

# 3 ▸ Firewall ruleset
- name: Render nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    mode: "0644"
    validate: "nft -c -f %s"
  register: nft_cfg

- import_tasks: ipsets.yml         # auto-create @"netify:*" sets

- name: Reload nftables rules
  ansible.builtin.command: nft -f /etc/nftables.conf
  when: nft_cfg.changed
  notify: enable_nftables          # handled below

# 4 ▸ Optional QoS
- import_tasks: cake.yml
- import_tasks: qos_persist.yml  # Add this line