---
# All handlers consolidated & deduplicated

- name: enable_nftables            # <- exact match for notify
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    enabled: yes                   # make it start at boot

- name: Apply netplan              # still used by netplan.yml
  ansible.builtin.command: netplan apply
  when: ansible_virtualization_role != "guest"

- name: Reload nftables            # template re-parsed without restart
  ansible.builtin.command: nft -f /etc/nftables.conf
  become: yes

- name: Restart netifyd
  ansible.builtin.systemd:
    name: netifyd
    state: restarted
